using NUnit.Framework.Interfaces;
using System.Text;

namespace Assesment.Tests
{
    [Order(9999)]
    public class FinalResult
    {
        [Test]
        public void Test()
        {
            //Dictionary<string, (int TotalAssertions, int PassedAssertions, int FailedAssertions)> testResults = new();
            StringBuilder resultBuilder = new StringBuilder();
            //var Success = 0;
            //var Fail = 0;

            foreach (var test in ExamResults.ExamResultList)
            {
                //var testName = test.Test.FullName;

                //int totalAssertions = test.Result.Assertions.Count();
                //int passedAssertions = 0;
                //int failedAssertions = 0;

                var testName = test.Test.FullName;
                int totalAssertions = test.AssertCount;
                var Success = test.AssertCount - test.Result.Assertions.Count();
                var Fail = test.Result.Assertions.Count();

                resultBuilder.AppendLine($"Test: {testName}");
                resultBuilder.AppendLine($"Total Assertions: {totalAssertions}");
                resultBuilder.AppendLine($"Passed Assertions: {Success}");
                resultBuilder.AppendLine($"Failed Assertions: {Fail}");
                resultBuilder.AppendLine();
                //foreach (var assertion in test.Result.Assertions)
                //{
                //    if (assertion.Status == AssertionStatus.Passed)
                //    {
                //        passedAssertions++;
                //    }
                //    else if (assertion.Status == AssertionStatus.Failed)
                //    {
                //        failedAssertions++;
                //    }
                //}

                //testResults.Add(testName, (totalAssertions, passedAssertions, failedAssertions));
                Console.WriteLine(resultBuilder.ToString()); // Print the result
            }

        }

        //[Test]
        //public void Result()
        //{
        //    var AssetSuccess = 0;
        //    var AssetFail = 0;
        //    foreach (var e in ExamResults.ExamResultList)
        //    {
        //        AssetFail += e.Result.Assertions.Count();
        //        AssetSuccess += e.AssertCount - e.Result.Assertions.Count();
        //    }
        //    //Assert.Pass($"Assert Success: {AssetSuccess},Assert Fail = {AssetFail}");

        //    // Saving the message generated by Assert.Pass into a variable
        //    string passMessage = $"Assert Success: {AssetSuccess}, Assert Fail = {AssetFail}";

        //    // Print the message to the console
        //    //Console.WriteLine(passMessage);

        //    // Writing the message to a file (Optional)
        //    // System.IO.File.WriteAllText("test_result.txt", passMessage);

        //    // Assert.Pass will always pass the test
        //    Assert.Pass(passMessage);
        //}
    }
}
