using Assess.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Assesment.Tests
{
    [Order(9999)]
    public class FinalResult
    {

        [Test]
        public void Result()
        {
            var AssetSuccess = 0;
            var AssetFail = 0;
            foreach (var e in ExamResults.ExamResultList)
            {
                AssetFail += e.Result.Assertions.Count();
                AssetSuccess += e.AssertCount - e.Result.Assertions.Count();
            }
            //Assert.Pass($"Assert Success: {AssetSuccess},Assert Fail = {AssetFail}");

            // Saving the message generated by Assert.Pass into a variable
            string passMessage = $"Assert Success: {AssetSuccess}, Assert Fail = {AssetFail}";

            // Print the message to the console
            Console.WriteLine(passMessage);

            // Writing the message to a file (Optional)
            // System.IO.File.WriteAllText("test_result.txt", passMessage);

            // Assert.Pass will always pass the test
            Assert.Pass(passMessage);
        }
    }
}
