name: CI/CD On Push Workflow

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: read-all
    env:
      ACTIONS_STEP_DEBUG: true

    steps:
      - uses: actions/checkout@v3
      - name: Checkout Code
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}
          source-url: ${{ vars.NUGET_SOURCE_URL }}

      - name: Debug Root Directory
        run: ls -la

      - name: Dotnet restore solution
        run: dotnet restore AssessGrader.sln

      - name: Dotnet build solution
        run: dotnet build AssessGrader.sln

  test:
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      test-results: ${{ steps.test.outputs.test-results }}
    steps:
      - uses: actions/checkout@v3
      - name: Checkout Code
        uses: actions/setup-dotnet@v3
        with:
           dotnet-version: ${{ vars.DOTNET_VERSION }}
           source-url: ${{ vars.NUGET_SOURCE_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}

        # Replace this whichever way you build your code
      # - name: Build & Test dotnet code
      #   run: |
      #     dotnet restore
      #     dotnet build -c Release no-restore
      #     dotnet test -c Release --no-restore --no-build --logger trx --results-directory ./TestResults || true
      # # Using the trx-parser action
      # - name: Parse Trx files
      #   uses: NasAmin/trx-parser@v0.1
      #   id: trx-parser
      #   with:
      #     TRX_PATH: ${{ github.workspace }}/TestResults #This should be the path to your TRX files
      #     REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}       

      - name: Test
        run: dotnet test ${{ vars.SOLUTION_PATH }} --logger "trx;LogFileName=test-results.trx" || true  *With this CI continue to run whether tests fail or not
        # run: dotnet test ${{ vars.SOLUTION_PATH }} --logger "trx;LogFileName=test-results.trx"
      - name: Install xmlstarlet
        run: sudo apt-get update && sudo apt-get install -y xmlstarlet

      - name: List Test Results Directory
        run: ls -la /home/runner/work/AssessmentSystem/AssessmentSystem/Assesment.Tests/TestResults/

      - name: Debug Test Results File Content
        run: cat /home/runner/work/AssessmentSystem/AssessmentSystem/Assesment.Tests/TestResults/test-results.trx

      - name: Get Test Results
        id: get_results
        run: |
          total_points=$(xmlstarlet sel -t -v "//Counters/@total" /home/runner/work/AssessmentSystem/AssessmentSystem/Assesment.Tests/TestResults/test-results.trx)
          passed=$(xmlstarlet sel -t -v "//Counters/@passed" /home/runner/work/AssessmentSystem/AssessmentSystem/Assesment.Tests/TestResults/test-results.trx)
          failed=$(xmlstarlet sel -t -v "//Counters/@failed" /home/runner/work/AssessmentSystem/AssessmentSystem/Assesment.Tests/TestResults/test-results.trx)
          echo "total-points=$total_points" >> $GITHUB_ENV
          echo "passed=$passed" >> $GITHUB_ENV
          echo "failed=$failed" >> $GITHUB_ENV
          echo "::set-output name=test-results::Total Points: $total_points Passed: $passed Failed: $failed"
      # - uses: actions/checkout@v4

      # - name: dotnet test with coverage
      #   run: dotnet test ${{ vars.SOLUTION_PATH }} --logger trx --configuration Release || true

      # - name: Process trx reports with default
      #   if: always()
      #   # You may also reference just the major or major.minor version
      #   uses: im-open/process-dotnet-test-results@v2.4.0
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Debug Test Results Directory
      #   run: ls -la /home/runner/work/AssessmentSystem/AssessmentSystem/Assesment.Tests/TestResults

      # - name: Check Test Results File
      #   id: check_results
      #   run: |
      #     ls -la   # Debugging statement
      #     if [ -f /home/runner/work/AssessmentSystem/AssessmentSystem/Assesment.Tests/TestResults/test-results.trx ]; then
      #       echo "test-results-exist=true" >> $GITHUB_ENV
      #     else
      #       echo "test-results-exist=false" >> $GITHUB_ENV
      #     fi


      # - name: Get Test Results
      #   id: get_results
      #   if: env.test-results-exist == 'true'
      #   run: |
      #     test_results=$(cat /home/runner/work/AssessmentSystem/AssessmentSystem/Assesment.Tests/TestResults/test-results.trx | grep -oP '(?<=<StdOut>).*?(?=</StdOut>)')
      #     echo "test-results=$test_results" >> $GITHUB_ENV

      # - name: Test Report
      #   uses: dorny/test-reporter@v1
      #   if: always()
      #   with:
      #     name: DotNET Tests
      #     path: "**/test-results.trx"
      #     reporter: dotnet-trx
      #     fail-on-error: 'false'
      #     only-summary: 'false'


