name: CI/CD On Push Workflow

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: write
    env:
      ACTIONS_STEP_DEBUG: true

    steps:
      - uses: actions/checkout@v3
      - name: Checkout Code
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}
          source-url: ${{ vars.NUGET_SOURCE_URL }}

      - name: Dotnet restore solution
        run: dotnet restore AssessGrader.sln

      - name: Dotnet build solution
        run: dotnet build AssessGrader.sln

  get-result:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      test_result: ${{ steps.get-result-output.outputs.test_result }}
    permissions: write-all

    steps:
      - uses: actions/checkout@v3
      - name: Checkout Code
        uses: actions/setup-dotnet@v3
        with:
           dotnet-version: ${{ vars.DOTNET_VERSION }}
           source-url: ${{ vars.NUGET_SOURCE_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run Test Scenarios
        run: dotnet test ${{ vars.SOLUTION_PATH }} --logger "trx;LogFileName=test-results.trx" || true  *With this CI continue to run whether tests fail or not

      - name: Get Results
        id: get-result-output
        run: |
            xml_file="/home/runner/work/AssessmentSystem/AssessmentSystem/Assesment.Tests/TestResults/test-results.trx"
            test_result=$(grep -o '<StdOut>.*</StdOut>' "$xml_file" | sed 's/<StdOut>\(.*\)<\/StdOut>/\1/')
            echo "::set-output name=test_result::$test_result"
   
      - name: Print Test Results
        run: |
          echo "${{ steps.get-result-output.outputs.test_result }}"

  send-notification:
    needs: get-result
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get last pull request number
        id: get-pr-number
        run: |
          pr_number=$(git log -1 --pretty=format:%s | grep -oP '#\d+')
          pr_number=${pr_number//#/}  # Remove '#' symbol
          echo "::set-output name=pr_number::$pr_number"    
     
      - name: Add Comment
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ steps.get-pr-number.outputs.pr_number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "${{ steps.get-result-output.outputs.test_result }}" 
              })
