name: CI/CD Send GitHub Notification

on:
  workflow_run:
    workflows: ["CI/CD On Push Workflow"]
    types:
     - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  send-notification:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Get test results
        id: get-results
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB.TOKEN }}
          script: |
            const { data: runs } = await github.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.event.workflow_run.id }}
            });
            const tests = runs.jobs.flatMap(job => job.steps.filter(step => step.name === 'Run unit tests'));
            return tests.map(test => test.conclusion).join(", ");

      - name: Send Github notification
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const body = '
              All unit tests have passed successfully.
              Test Results: ${{ steps.get-results.outputs.reuslt }}
              ';
             await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.workflow_run.id }},
              body: body
             });
