name: CI/CD Send GitHub Notification

on:
  workflow_run:
    workflows:
      - CI/CD On Push Workflow
    types:
      - completed

  workflow_dispatch: 

jobs:
  send-notification:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
